version: '3.5'

networks:
  training:
    external: true
    name: training

services:
  company-read:
    build:
      context: .
      dockerfile: docker/Dockerfile
      target: production
    environment:
      - QUERY_SIZE=1000
      - ELASTIC_URL=http://elastic_search:9200
    ports:
      - "8080:8080"
    networks:
      - training